package threads;

public class ResultTask extends Thread{
    public void run(){
        System.out.println("Results generated by:" + Thread.currentThread().getName());
    }

    static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run();//normal execution -> always the main thread
        t1.start();//multi threading -> THREAD 0,THREAD 1 SOOOONNN
        //start() internally calls run()
        //thread cannot be started twice
    }
}
